name: qutip-paper
channels:
- conda-forge
dependencies:
- python==3.10
- pip==22.1.2
- qutip==5.1.0
- numpy==1.26.0
- scipy==1.14.1
- matplotlib==3.9.3
- mpmath==1.2.1
- pytest==7.1.2
- jax==0.4.35
- diffrax==0.6.1
- jaxlib==0.4.35
- tqdm
- git
- pip:
     - qutip-qip==0.4.0
     - qutip-jax==0.0.1
     - qutip-qtrl==0.1.3
     - qutip-qoc==0.1.1
